//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueHub.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IssueHub.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Acknowledgements に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Acknowledgements {
            get {
                return ResourceManager.GetString("Acknowledgements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add To Favorites に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AddToFavorites {
            get {
                return ResourceManager.GetString("AddToFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Apply に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Assigned に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Assigned {
            get {
                return ResourceManager.GetString("Assigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Assignees に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Assignees {
            get {
                return ResourceManager.GetString("Assignees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Body に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Body {
            get {
                return ResourceManager.GetString("Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close Issue に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CloseIssue {
            get {
                return ResourceManager.GetString("CloseIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Closing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Closing {
            get {
                return ResourceManager.GetString("Closing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Comment に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Created に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Done に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to logout? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DoYouWantToLogout {
            get {
                return ResourceManager.GetString("DoYouWantToLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit Body に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EditBody {
            get {
                return ResourceManager.GetString("EditBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit Issue に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EditIssue {
            get {
                return ResourceManager.GetString("EditIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit #{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EditIssueNumberFormat {
            get {
                return ResourceManager.GetString("EditIssueNumberFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Favorites に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Favorites {
            get {
                return ResourceManager.GetString("Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GitHub に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GitHub {
            get {
                return ResourceManager.GetString("GitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hide Closed Issues に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HideClosedIssues {
            get {
                return ResourceManager.GetString("HideClosedIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IssueHub に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IssueHub {
            get {
                return ResourceManager.GetString("IssueHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Labels に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Labels {
            get {
                return ResourceManager.GetString("Labels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Logging in に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LoggingIn {
            get {
                return ResourceManager.GetString("LoggingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Login に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Logout に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Issue に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewIssue {
            get {
                return ResourceManager.GetString("NewIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Opening に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Opening {
            get {
                return ResourceManager.GetString("Opening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove From Favorites に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RemoveFromFavorites {
            get {
                return ResourceManager.GetString("RemoveFromFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reopen Issue に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReopenIssue {
            get {
                return ResourceManager.GetString("ReopenIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Repositories に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Repositories {
            get {
                return ResourceManager.GetString("Repositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sending に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Sending {
            get {
                return ResourceManager.GetString("Sending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Closed Issues に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShowClosedIssues {
            get {
                return ResourceManager.GetString("ShowClosedIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Smart Lists に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SmartLists {
            get {
                return ResourceManager.GetString("SmartLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Submit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Title に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Username に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
